# Generated by Django 6.0.2 on 2026-02-19 19:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_expense_category_customer_sale_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='current_odometer',
            field=models.IntegerField(default=0, help_text='Last recorded km'),
        ),
        migrations.AddField(
            model_name='truck',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TripLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_odometer', models.IntegerField()),
                ('end_odometer', models.IntegerField(blank=True, null=True)),
                ('fuel_used', models.DecimalField(blank=True, decimal_places=2, help_text='Liters', max_digits=8, null=True)),
                ('distance_km', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sale')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='core.truck')),
            ],
        ),
    ]
