# Generated by Django 6.0.2 on 2026-02-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_truck_current_odometer_truck_last_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('raw_materials', 'Raw Materials & Inputs (cement, sand, aggregates, timber)'), ('production_labor', 'Production Labor & Wages'), ('truck_operations', 'Truck Operations (fuel, diesel, petrol, delivery)'), ('truck_maintenance', 'Truck Repairs & Maintenance'), ('administration', 'Administration (rent, electricity, office supplies, admin salaries)'), ('depreciation', 'Depreciation (equipment, machinery, trucks)'), ('other_allowable', 'Other Allowable Deductions')], default='other_allowable', max_length=50),
        ),
    ]
