# Generated by Django 5.2.13 on 2026-04-25 10:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Stock Purchase'), ('sale', 'Sale'), ('production_in', 'Production Output'), ('production_out', 'Raw Material Used'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_before', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='core.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='core.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'created_at'], name='core_invent_product_0df28e_idx'), models.Index(fields=['branch', 'created_at'], name='core_invent_branch__96ce47_idx')],
            },
        ),
    ]
