# Generated by Django 5.2.13 on 2026-09-19 20:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inventorylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_source',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_mobile', 'Bank / Mobile Money')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='BankDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_date', models.DateField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, help_text='Deposit slip number or bank reference', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_deposits', to='core.branch')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-deposit_date'],
            },
        ),
    ]
